## Chapter04 추측통계의 기본
_ 일부 데이터로부터 전체의 통계적 성질을 추측하는 방식이 "추측통계"입니다.
- 추측통계와 비교하여 2장과 3장에서 다른 통계를 "기술통계"라고 합니다. 

### 4.2 확률 모형 
### 4.3 추측통계의 확률 


In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

%precision 3
%matplotlib inline

In [3]:
df = pd.read_csv('../data/ch4_scores400.csv')
scores = np.array(df['score'])
scores[:10]

array([76, 55, 80, 80, 74, 61, 81, 76, 23, 80], dtype=int64)

### 4.1 모집단과 표본 
- 추측통계에서는 관측 대상 전체의 통계적 성질을 그 관측 대상의 일부분만 사용하여 추측합니다. 
- 이때, 추측하고 싶은 관측 대상 전체를 모집단(population)이라고 하고, 추측에 사용하는 관측 대상의 일부분을 표본(sample)이라 합니다 
- 모집단에서 표본을 골라내는 일을 표본추출(sampling)이라 하고, 골라낸 표본의 수를 '표본크기' 또는 '샘플사이즈'라고 합니다 
- 표본을 바탕으로 계싼한 평균이나 분산, 상관계수 등을 '표본통계량'이라고 하고, 모집단의 평균이나 분산, 상관계수 등을 '모수'라고 합니다. 
- 표본평균으로 모평균을 추측할 때, '표본평균은 모평균의 추정량(estimator)라고 합니다.' 실제 표본의 데이터를 이용하여 계산한 결과를 '추정값estimator'라고 합니다. 

### 4.1.1 표본추출 방법
- 임의료 표본을 추출하는 방법을 '무작위추출(random sampling)'이라고 합니다 
- 복원추출: 여러차례 동일한 표본을 선택하는 추출방법 
- 비복원추출: 동일한 표본은 한번만 선택하는 방법

In [6]:
np.random.choice([1,2,3],3)

array([1, 1, 2])

In [31]:
np.random.choice([1,2,3],3,replace=False)

array([3, 1, 2])

In [44]:
# 난수 seed사용 
np.random.seed(0)
np.random.choice([1,2,3],3)

array([1, 2, 1])

In [65]:
np.random.seed(0)
sample = np.random.choice(scores,20)
sample.mean()

70.4

In [56]:
scores.mean()

69.53

In [76]:
for i in range(5):
    smaple = np.random.choice(scores,20)
    print(f'{i+1}번째 무작위추출로 얻은 표본평균',sample.mean())

1번째 무작위추출로 얻은 표본평균 70.4
2번째 무작위추출로 얻은 표본평균 70.4
3번째 무작위추출로 얻은 표본평균 70.4
4번째 무작위추출로 얻은 표본평균 70.4
5번째 무작위추출로 얻은 표본평균 70.4
