## Chapter04 추측통계의 기본
_ 일부 데이터로부터 전체의 통계적 성질을 추측하는 방식이 "추측통계"입니다.
- 추측통계와 비교하여 2장과 3장에서 다른 통계를 "기술통계"라고 합니다. 

### 4.2 확률 모형 
### 4.3 추측통계의 확률 


In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

%precision 3
%matplotlib inline

In [2]:
df = pd.read_csv('../data/ch4_scores400.csv')
scores = np.array(df['score'])
# scores[:10]

### 4.1 모집단과 표본 
- 추측통계에서는 관측 대상 전체의 통계적 성질을 그 관측 대상의 일부분만 사용하여 추측합니다. 
- 이때, 추측하고 싶은 관측 대상 전체를 모집단(population)이라고 하고, 추측에 사용하는 관측 대상의 일부분을 표본(sample)이라 합니다 
- 모집단에서 표본을 골라내는 일을 표본추출(sampling)이라 하고, 골라낸 표본의 수를 '표본크기' 또는 '샘플사이즈'라고 합니다 
- 표본을 바탕으로 계싼한 평균이나 분산, 상관계수 등을 '표본통계량'이라고 하고, 모집단의 평균이나 분산, 상관계수 등을 '모수'라고 합니다. 
- 표본평균으로 모평균을 추측할 때, '표본평균은 모평균의 추정량(estimator)라고 합니다.' 실제 표본의 데이터를 이용하여 계산한 결과를 '추정값estimator'라고 합니다. 

### 4.1.1 표본추출 방법
- 임의료 표본을 추출하는 방법을 '무작위추출(random sampling)'이라고 합니다 
- 복원추출: 여러차례 동일한 표본을 선택하는 추출방법 
- 비복원추출: 동일한 표본은 한번만 선택하는 방법

In [3]:
np.random.choice([1,2,3],3)

array([1, 2, 3])

In [4]:
np.random.choice([1,2,3],3,replace=False)

array([3, 2, 1])

In [5]:
# 난수 seed사용 
np.random.seed(0)
np.random.choice([1,2,3],3)

array([1, 2, 1])

In [6]:
np.random.seed(0)
sample = np.random.choice(scores,20)
sample.mean()

70.4

In [7]:
scores.mean()

69.53

In [32]:
for i in range(5):
    sample = np.random.choice(scores, 20)
    print(f'{i+1}번째 무작위 추출로 얻은 표본평균', sample.mean())

1번째 무작위 추출로 얻은 표본평균 66.3
2번째 무작위 추출로 얻은 표본평균 68.7
3번째 무작위 추출로 얻은 표본평균 65.75
4번째 무작위 추출로 얻은 표본평균 70.75
5번째 무작위 추출로 얻은 표본평균 73.8


### 4.2 확률모형
- 확률모형: 확률을 사용한 무작위추출 또는 주사위를 모델링한 것
- 시행: 확률변수의 결과를 관측하는 것
- 실현값: 시행에 의해 관측되는 값
- 사건: 시행결과로 나타날 수 있는 일
- 근원사건: '눈이1'처럼 더 세부적으로 분해할 수 없는 사건

#### - 확률은 사건에 대해서 정의되는데,  '눈이1'이라는 사건에 대한 확률은 1/6,   '눈이홀수'라는 사건에 대한 확률은 1/2라는 식으로 대응됩니다. 

####'